services:
  database:
    image: "postgres:latest"
    container_name: database
    volumes:
      - database-data:/var/lib/postgresql/data
    ports:
      - 5432:5432

    environment:
      POSTGRES_DB: collaborative-whiteboard
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  whiteboard-app:
    build: # path to backend Dockerfile
    container_name: whiteboard-app
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/collaborative-whiteboard
      - SOCKET_SERVER=0.0.0.0
    ports:
      - 8080:8080
      - 8085:8085
      - 587:587
    depends_on:
      - database
    links:
      - database

  whiteboard-ui:
    build: # path to frontend Dockerfile
    container_name: whiteboard-ui
    ports:
      - 4200:80
    links:
      - whiteboard-app
volumes:
  database-data:
